# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de9905dec8776abb4d5f72d457238584bc32bc1e7801df4f3050dccec5aefed77483211c926213ed5b541ab912bc5a755f64add2612893948d37d8e85c15c8b8

test:
  secret_key_base: 1c81420240c9c4f7db2e740f702ba5a7149e5fe863d5c4120814c2429dd9a737171803af996cb1fe7c6c80247704612270437e9a2a6043acf2dc50f79cba1641

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
